# Generated by Django 2.1.7 on 2019-03-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('nim', models.IntegerField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], default=None, max_length=2)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('agama', models.CharField(choices=[('islam', 'Islam'), ('kristen', 'Kristen'), ('protestan', 'Protestan'), ('budha', 'Budha'), ('hindu', 'Hindu')], default=None, max_length=10)),
                ('alamat', models.TextField()),
            ],
        ),
    ]
